name: admin_panel_drive_smart
description: Admin panel for Drive Smart (Flutter web)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.13.0  # Keep the latest version of firebase_core
  firebase_auth: ^5.5.2
  firebase_auth_web: ^5.14.2
  firebase_storage: ^12.4.5  # Updated to a newer compatible version
  firebase_storage_web: ^3.4.0
  cloud_firestore: ^5.6.6
  google_sign_in: ^6.3.0
  provider: ^6.1.5
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  #table_calendar: ^3.2.0
  fl_chart: ^0.71.0
  geolocator: ^14.0.0
  geocoding: ^2.1.1
  google_maps_flutter: ^2.12.2

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.1.0
  dropdown_button2: ^2.3.9

  intl: ^0.19.0
  cached_network_image: ^3.3.1
  http: ^1.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/


#name: admin_panel_drive_smart
#description: Admin panel for Drive Smart (Flutter web)
#publish_to: 'none'
#version: 1.0.0+1
#
#environment:
#  sdk: ^3.7.2
#
#dependencies:
#  flutter:
#    sdk: flutter
#
#  firebase_auth_web: ^5.1.0
#  firebase_storage_web: ^3.4.0
#
#  firebase_core: ^2.0.0  # Latest stable version
#  firebase_auth: ^4.6.3
#  firebase_storage: ^11.2.4
#  cloud_firestore: ^4.8.2
#  google_sign_in: ^6.1.5
#
#  provider: ^6.0.5
#  image_picker: ^1.1.2
#  google_fonts: ^6.2.1
#  table_calendar: ^3.2.0
#  fl_chart: ^1.0.0
#  geolocator: ^14.0.0
#  geocoding: ^3.0.0
#  google_maps_flutter: ^2.0.0
#
#  cupertino_icons: ^1.0.6
#  flutter_svg: ^2.1.0  # For working with SVG images
#  dropdown_button2: ^2.3.9  # For dropdown buttons
#
#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  flutter_lints: ^5.0.0
#
#flutter:
#  uses-material-design: true
#  assets:
#    - assets/images/  # Add image assets if needed
