// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA9AjrLBwGuRokFWCezyhDKYpUrzjYaBw',
    appId: '1:96539269952:web:1af680268c3f5d7043b8a5',
    messagingSenderId: '96539269952',
    projectId: 'pfirebase-ea8fb',
    authDomain: 'pfirebase-ea8fb.firebaseapp.com',
    storageBucket: 'pfirebase-ea8fb.firebasestorage.app',
    measurementId: 'G-HWVNH72054',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDPXUNcU6gfdXXTVv4aUkvLYyVqFeB6tc',
    appId: '1:96539269952:android:84b7b3aa7faba8e443b8a5',
    messagingSenderId: '96539269952',
    projectId: 'pfirebase-ea8fb',
    storageBucket: 'pfirebase-ea8fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNHpGq0G2M30rvQv63jMN_8QHaLHmktUw',
    appId: '1:96539269952:ios:4ddbebee1f9cf9a843b8a5',
    messagingSenderId: '96539269952',
    projectId: 'pfirebase-ea8fb',
    storageBucket: 'pfirebase-ea8fb.firebasestorage.app',
    androidClientId: '96539269952-rs07d6qocdvv44626784kac2fh36b2e7.apps.googleusercontent.com',
    iosClientId: '96539269952-d04la1tl7ndvumidu10vv8pc7u5g6dd0.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPanelDriveSmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNHpGq0G2M30rvQv63jMN_8QHaLHmktUw',
    appId: '1:96539269952:ios:4ddbebee1f9cf9a843b8a5',
    messagingSenderId: '96539269952',
    projectId: 'pfirebase-ea8fb',
    storageBucket: 'pfirebase-ea8fb.firebasestorage.app',
    androidClientId: '96539269952-rs07d6qocdvv44626784kac2fh36b2e7.apps.googleusercontent.com',
    iosClientId: '96539269952-d04la1tl7ndvumidu10vv8pc7u5g6dd0.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPanelDriveSmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA9AjrLBwGuRokFWCezyhDKYpUrzjYaBw',
    appId: '1:96539269952:web:1af680268c3f5d7043b8a5',
    messagingSenderId: '96539269952',
    projectId: 'pfirebase-ea8fb',
    authDomain: 'pfirebase-ea8fb.firebaseapp.com',
    storageBucket: 'pfirebase-ea8fb.firebasestorage.app',
    measurementId: 'G-HWVNH72054',
  );

}